# Generated by Django 3.1.1 on 2020-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='body',
        ),
        migrations.AlterField(
            model_name='animal',
            name='special',
            field=models.TextField(blank=True),
        ),
    ]
