# Generated by Django 3.1.1 on 2020-09-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0003_auto_20200924_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='author',
            new_name='shelter',
        ),
    ]
