# Generated by Django 3.1.1 on 2020-09-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0006_auto_20200925_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='owner',
        ),
    ]
