# Generated by Django 3.1.1 on 2020-09-27 10:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal_shelter', '0003_auto_20200926_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AddField(
            model_name='animal',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Возвраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Рост(см)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Приют'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='special',
            field=models.TextField(blank=True, null=True, verbose_name='Особые приметы'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Вес(кг)'),
        ),
    ]
